In [1]:
import pandas as pd
import numpy as np

# NLP tools
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# Load CSV file
df = pd.read_csv("AndroidQuestions.csv")

# Preview data
df.head()

    created_utc  ...  distinguished
0  1.352763e+09  ...            NaN
1  1.313077e+09  ...            NaN
2  1.347150e+09  ...            NaN
3  1.364054e+09  ...            NaN
4  1.367351e+09  ...            NaN

[5 rows x 22 columns]

In [4]:
stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    
    # Lowercase
    text = text.lower()
    
    # Remove numbers and punctuation
    text = re.sub('[^a-zA-Z]', ' ', text)
    
    # Tokenize
    words = text.split()
    
    # Remove stopwords and apply stemming
    words = [stemmer.stem(word) for word in words if word not in stop_words]
    
    return " ".join(words)

In [6]:
print(df.head())
print(df.columns)

    created_utc  ...  distinguished
0  1.352763e+09  ...            NaN
1  1.313077e+09  ...            NaN
2  1.347150e+09  ...            NaN
3  1.364054e+09  ...            NaN
4  1.367351e+09  ...            NaN

[5 rows x 22 columns]
Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Example text data
X = [
    "This movie is great",
    "I love this film",
    "This film is terrible",
    "Amazing acting and story",
    "Bad movie and poor acting"
]

# Create the vectorizer
vectorizer = TfidfVectorizer(max_features=5000)

# Transform text into TF-IDF features
X_vectorized = vectorizer.fit_transform(X)

# Optional: check the shape of the result
print(X_vectorized.shape)

(5, 13)

In [9]:
vectorizer = TfidfVectorizer(max_features=5000)

X_vectorized = vectorizer.fit_transform(X)

In [12]:
df.head()

    created_utc  ...  distinguished
0  1.352763e+09  ...            NaN
1  1.313077e+09  ...            NaN
2  1.347150e+09  ...            NaN
3  1.364054e+09  ...            NaN
4  1.367351e+09  ...            NaN

[5 rows x 22 columns]

In [17]:
import pandas as pd

data = pd.read_csv("AndroidQuestions.csv")

print(data.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [21]:
data.head()

    created_utc  ...  distinguished
0  1.352763e+09  ...            NaN
1  1.313077e+09  ...            NaN
2  1.347150e+09  ...            NaN
3  1.364054e+09  ...            NaN
4  1.367351e+09  ...            NaN

[5 rows x 22 columns]

In [24]:
# Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

# Load dataset
data = load_iris()

# Define features (X) and labels (y)
X = data.data
y = data.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = RandomForestClassifier(random_state=42)

# Train model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate model
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30