In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

# Feature extraction
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("AndroidGaming.csv")

# View first rows
df.head()

    created_utc  ...  distinguished
0  1.363594e+09  ...      moderator
1  1.361114e+09  ...            NaN
2  1.372334e+09  ...            NaN
3  1.370198e+09  ...            NaN
4  1.361420e+09  ...            NaN

[5 rows x 22 columns]

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_utc             1000 non-null   float64
 1   score                   1000 non-null   int64
 2   domain                  1000 non-null   str
 3   id                      1000 non-null   str
 4   title                   1000 non-null   str
 5   author                  979 non-null    str
 6   ups                     1000 non-null   int64
 7   downs                   1000 non-null   int64
 8   num_comments            1000 non-null   int64
 9   permalink               1000 non-null   str
 10  selftext                359 non-null    str
 11  link_flair_text         1 non-null      str
 12  over_18                 1000 non-null   bool
 13  thumbnail               1000 non-null   str
 14  subreddit_id            1000 non-null   str
 15  edited                  1000 non-null   str
 16  link_flair_css_class    1 non-null      str
 17  author_flair_css_class  112 non-null    str
 18  is_self                 1000 non-null   bool
 19  name                    1000 non-null   str
 20  url                     1000 non-null   str
 21  distinguished           3 non-null      str
dtypes: bool(2), float64(1), int64(4), str(15)
memory usage: 674.9 KB

In [4]:
# Check missing values
df.isnull().sum()

created_utc                 0
score                       0
domain                      0
id                          0
title                       0
author                     21
ups                         0
downs                       0
num_comments                0
permalink                   0
selftext                  641
link_flair_text           999
over_18                     0
thumbnail                   0
subreddit_id                0
edited                      0
link_flair_css_class      999
author_flair_css_class    888
is_self                     0
name                        0
url                         0
distinguished             997
dtype: int64

In [5]:
# Download NLTK resources (run once)
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [6]:
def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation and numbers
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenize
    words = text.split()

    # Remove stopwords and lemmatize
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    return " ".join(words)

In [8]:
print(df.columns)
df.head()

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

    created_utc  ...  distinguished
0  1.363594e+09  ...      moderator
1  1.361114e+09  ...            NaN
2  1.372334e+09  ...            NaN
3  1.370198e+09  ...            NaN
4  1.361420e+09  ...            NaN

[5 rows x 22 columns]

In [9]:
df.columns

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [11]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [13]:
print(df.head())
print(df.columns)

    created_utc  ...  distinguished
0  1.363594e+09  ...      moderator
1  1.361114e+09  ...            NaN
2  1.372334e+09  ...            NaN
3  1.370198e+09  ...            NaN
4  1.361420e+09  ...            NaN

[5 rows x 22 columns]
Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [16]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [20]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [26]:
print(data.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [32]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [35]:
print(hasattr(vectorizer, "vocabulary_"))

False