In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [2]:
# Load Beatmatch dataset
df = pd.read_csv("Beatmatch.csv")

# Preview the data
df.head()

    created_utc  ...  distinguished
0  1.371507e+09  ...            NaN
1  1.353445e+09  ...            NaN
2  1.343056e+09  ...            NaN
3  1.362585e+09  ...            NaN
4  1.368123e+09  ...            NaN

[5 rows x 22 columns]

In [3]:
# Dataset structure
df.info()

# Summary statistics
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_utc             1000 non-null   float64
 1   score                   1000 non-null   int64
 2   domain                  1000 non-null   str
 3   id                      1000 non-null   str
 4   title                   1000 non-null   str
 5   author                  960 non-null    str
 6   ups                     1000 non-null   int64
 7   downs                   1000 non-null   int64
 8   num_comments            1000 non-null   int64
 9   permalink               1000 non-null   str
 10  selftext                793 non-null    str
 11  link_flair_text         37 non-null     str
 12  over_18                 1000 non-null   bool
 13  thumbnail               1000 non-null   str
 14  subreddit_id            1000 non-null   str
 15  edited                  1000 non-null   str
 16  link_flair_css_class    0 non-null      float64
 17  author_flair_css_class  0 non-null      float64
 18  is_self                 1000 non-null   bool
 19  name                    1000 non-null   str
 20  url                     1000 non-null   str
 21  distinguished           49 non-null     str
dtypes: bool(2), float64(3), int64(4), str(13)
memory usage: 1.0 MB

created_utc                  0
score                        0
domain                       0
id                           0
title                        0
author                      40
ups                          0
downs                        0
num_comments                 0
permalink                    0
selftext                   207
link_flair_text            963
over_18                      0
thumbnail                    0
subreddit_id                 0
edited                       0
link_flair_css_class      1000
author_flair_css_class    1000
is_self                      0
name                         0
url                          0
distinguished              951
dtype: int64

In [4]:
# Select numeric columns
features = df.select_dtypes(include=['float64','int64'])

features.head()

    created_utc  score  ...  link_flair_css_class  author_flair_css_class
0  1.371507e+09    131  ...                   NaN                     NaN
1  1.353445e+09     99  ...                   NaN                     NaN
2  1.343056e+09     94  ...                   NaN                     NaN
3  1.362585e+09     92  ...                   NaN                     NaN
4  1.368123e+09     61  ...                   NaN                     NaN

[5 rows x 7 columns]

In [5]:
scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

scaled_features = pd.DataFrame(scaled_features, columns=features.columns)

scaled_features.head()

/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/sklearn/utils/extmath.py:1207: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/sklearn/utils/extmath.py:1212: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/Users/adnanaltimeemy/miniconda3/envs/coding/lib/python3.12/site-packages/sklearn/utils/extmath.py:1236: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

   created_utc      score  ...  link_flair_css_class  author_flair_css_class
0     1.059126  12.870447  ...                   NaN                     NaN
1    -0.154553   9.491850  ...                   NaN                     NaN
2    -0.852622   8.963944  ...                   NaN                     NaN
3     0.459649   8.752782  ...                   NaN                     NaN
4     0.831727   5.479767  ...                   NaN                     NaN

[5 rows x 7 columns]

In [7]:
df.isna().sum()

created_utc                  0
score                        0
domain                       0
id                           0
title                        0
author                      40
ups                          0
downs                        0
num_comments                 0
permalink                    0
selftext                   207
link_flair_text            963
over_18                      0
thumbnail                    0
subreddit_id                 0
edited                       0
link_flair_css_class      1000
author_flair_css_class    1000
is_self                      0
name                         0
url                          0
distinguished              951
dtype: int64

In [10]:
df.isna().sum()

created_utc                  0
score                        0
domain                       0
id                           0
title                        0
author                      40
ups                          0
downs                        0
num_comments                 0
permalink                    0
selftext                   207
link_flair_text            963
over_18                      0
thumbnail                    0
subreddit_id                 0
edited                       0
link_flair_css_class      1000
author_flair_css_class    1000
is_self                      0
name                         0
url                          0
distinguished              951
dtype: int64

In [13]:
print(df.shape)
print(scaled_features.shape)
print(df.head())

(1000, 22)
(0, 7)
    created_utc  ...  distinguished
0  1.371507e+09  ...            NaN
1  1.353445e+09  ...            NaN
2  1.343056e+09  ...            NaN
3  1.362585e+09  ...            NaN
4  1.368123e+09  ...            NaN

[5 rows x 22 columns]

In [14]:
df = df.dropna()

In [15]:
print(df.isna().sum())

created_utc               0
score                     0
domain                    0
id                        0
title                     0
author                    0
ups                       0
downs                     0
num_comments              0
permalink                 0
selftext                  0
link_flair_text           0
over_18                   0
thumbnail                 0
subreddit_id              0
edited                    0
link_flair_css_class      0
author_flair_css_class    0
is_self                   0
name                      0
url                       0
distinguished             0
dtype: int64

In [17]:
print(df.columns.tolist())

['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups', 'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text', 'over_18', 'thumbnail', 'subreddit_id', 'edited', 'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name', 'url', 'distinguished']

In [18]:
df.to_csv("Beatmatch_clustered.csv", index=False)